import Link from 'next/link';
import {ArrowRight,ArrowUpRight,Globe2,GraduationCap} from 'lucide-react';
import {projects,profile} from '@/content/profile';
import {Constellation} from '@/components/constellation';
import {jsonLd,person,siteUrl} from '@/lib/site';
import {Portrait} from '@/components/portrait';
import {getProfileMedia,showPhotoHints} from '@/lib/profile-media';
export default async function Home(){const {portrait}=await getProfileMedia();
const profilePage={'@context':'https://schema.org','@type':'ProfilePage',url:siteUrl,dateModified:profile.updated,mainEntity:{...person,...(portrait?{image:`${siteUrl}${portrait.src}`}:{})}};
return <>
<script type="application/ld+json" dangerouslySetInnerHTML={jsonLd(profilePage)}/>
<section className="hero"><div className="hero-copy"><p className="eyebrow"><span/> NIMRA ZAHID · INTERNATIONAL RELATIONS · EDUCATION</p><h1>Afghanistan isn’t a buffer.<br/><em>It’s a driver.</em></h1><p className="hero-subline">Regions connect. Ideas travel. Understanding matters.</p><p className="hero-intro">I’m <strong>Nimra Zahid</strong>, an International Relations researcher and educator. My research argues that Afghanistan is an instigator of regional security dynamics in South and Central Asia, not simply an insulator between them. I also teach young people how the world fits together.</p><div className="hero-person"><Portrait photo={portrait} variant="hero" hint={showPhotoHints} priority/><p className="credentials">MA International Relations (Merit) · MPhil International Relations<br/>Educator since 2015 · Northampton, UK</p></div><div className="actions"><Link className="button" href="/research">Explore my research <ArrowUpRight size={18}/></Link><a className="text-link" href="/cv.pdf">Download CV <ArrowRight size={17}/></a></div></div><Constellation/></section>
<div className="at-a-glance"><div><strong>10+</strong><span>years in education</span></div><div><strong>2</strong><span>countries</span></div><div><strong>3</strong><span>degrees in IR</span></div><div><strong>6</strong><span>undergraduate modules</span></div><div><span className="glance-label">A perspective shaped by</span><span>research & the classroom</span></div></div>
<section className="section"><div className="section-heading"><div><p className="eyebrow">01 / TWO STRANDS, ONE PERSPECTIVE</p><h2>Connections are the throughline.</h2></div><Link className="text-link" href="/about">A little more about me <ArrowUpRight size={17}/></Link></div><div className="theme-grid two"><Link className="theme-card" href="/research"><div className="theme-top"><Globe2 size={30}/><span className="mono">RESEARCH</span></div><h3>Regional security<br/>& Afghanistan</h3><p>I ask why Afghanistan should be understood as an instigator, not simply an insulator, in its regional security complex.</p><span className="card-bottom">Explore the argument <ArrowUpRight size={17}/></span></Link><Link className="theme-card" href="/teaching"><div className="theme-top"><GraduationCap size={30}/><span className="mono">EDUCATION</span></div><h3>Teaching, inclusion<br/>& possibility</h3><p>Over ten years teaching across Pakistan and England, from undergraduate International Relations to specialist SEMH provision.</p><span className="card-bottom">My approach to teaching <ArrowUpRight size={17}/></span></Link></div></section>
<section className="section selected"><div className="section-heading"><div><p className="eyebrow">02 / A DEVELOPING RESEARCH AGENDA</p><h2>From insulator to <em>instigator.</em></h2></div><Link className="text-link" href="/research">View research <ArrowUpRight size={17}/></Link></div><div className="project-grid">{projects.map((p,i)=><Link className="project-card" href={`/research/${p.slug}`} key={p.slug}><div className="project-number">0{i+1}<ArrowUpRight size={20}/></div><p className="eyebrow">{p.type} · {p.year}</p><h3>{p.shortTitle}</h3><p>{p.teaser}</p><span className="card-bottom">Read more <ArrowRight size={16}/></span></Link>)}</div></section>
<section className="contact-band"><p className="eyebrow">LET’S CONNECT</p><h2>New questions.<br/><em>Shared possibilities.</em></h2><p>Open to doctoral research opportunities, collaboration and speaking.</p><Link className="button" href="/contact">Start a conversation <ArrowUpRight size={18}/></Link></section></>}
