export const profile = {
 name:'Nimra Zahid', updated:'2026-09-24', preview:true, email:'', location:'Northampton, UK',
 role:'International Relations researcher & educator',
 languages:['English','Urdu','Punjabi'],
};
export const education = [
 {title:'MA International Relations',institution:'University of Northampton',dates:'September 2023 – November 2024',result:'Merit',detail:'Awarded 27 November 2024. Dissertation: Deconstructing the Role of Afghanistan in Regional Security Complex Theory.'},
 {title:'MPhil International Relations',institution:'National Defence University, Islamabad',dates:'Spring 2016 – Fall 2017',result:'CGPA 3.53 / 4.00',detail:'Conferred December 2018. Research on Russia–Afghanistan relations and regional stability. Formal thesis title awaiting confirmation.'},
 {title:'BS International Relations',institution:'Lahore College for Women University',dates:'2011 – 2015',result:'CGPA 3.24 / 4.00',detail:'Four-year degree; conferred May 2016.'},
];
export const teaching = [
 {title:'Geography & History Teacher · Form Tutor',institution:'Specialist SEMH school, Northamptonshire',dates:'February 2025 – present',detail:'KS3–4 Geography and History in specialist social, emotional and mental health provision. Adapting teaching and resources to individual learning needs.'},
 {title:'Geography & Science Teacher',institution:'Abbeyfield School, Northampton · via Teaching Personnel',dates:'February 2024 – February 2025',detail:'Secondary Geography and Science teaching in England.'},
 {title:'Visiting Faculty · International Relations',institution:'University of Gujrat, Mandi Bahauddin campus',dates:'September 2019 – March 2022',detail:'Taught six undergraduate modules, including Foreign Policy Analysis and Research Methodology. Served as Student Affairs Sub-in-Charge and led the Blood Donation Society.'},
 {title:'Secondary Teacher · Humanities & Social Studies',institution:'Beaconhouse School System, Pakistan',dates:'September 2015 – March 2023',detail:'Humanities and Social Studies teaching. This role overlapped with visiting university teaching.'},
];
export const projects = [
 {slug:'afghanistan-regional-security',title:'Deconstructing the Role of Afghanistan in Regional Security Complex Theory',shortTitle:'Afghanistan: from insulator to instigator',year:2024,type:'MA dissertation',institution:'University of Northampton',summary:'I examine Afghanistan as a driver of regional security dynamics, rather than a buffer between neighbouring security complexes.',question:'How does Afghanistan shape the security relationships of the regions around it?',argument:'My research challenges the classification of Afghanistan as an “insulator” within Regional Security Complex Theory and explores its role as an “instigator” of regional security dynamics.',method:'Theory-driven analysis using Regional Security Complex Theory (RSCT).',note:'This overview is drawn from the supplied content plan. The final abstract, methodology and key findings are awaiting author review.',kind:'Thesis'},
 {slug:'russia-afghanistan-relations',title:'Russia–Afghanistan relations and regional stability',shortTitle:'Russia, Afghanistan & regional stability',year:2018,type:'MPhil thesis',institution:'National Defence University, Islamabad',summary:'I explore Russia–Afghanistan relations and their implications for regional stability, establishing the foundation for my continuing regional security research.',question:'How do Russia–Afghanistan relations influence regional stability?',argument:'This project examines the relationship between Russia and Afghanistan within the wider context of regional security.',method:'The detailed methodology will be added following review of the thesis.',note:'A descriptive title is used here. The formal thesis title, including “Counter” versus “Contours” in the transcript, requires confirmation.',kind:'Thesis'},
 {slug:'istanbul-conference-2020',title:'The Global War on Terror, Afghanistan and Turkey',shortTitle:'Afghanistan, Turkey & the Global War on Terror',year:2020,type:'Conference paper',institution:'Istanbul International Social Science Conference',summary:'I presented research on the Global War on Terror and the roles of Afghanistan and Turkey in regional security at an international conference in Istanbul in June 2020.',question:'How have Afghanistan and Turkey shaped regional security in the context of the Global War on Terror?',argument:'This conference contribution connects my regional security interests with the roles of Afghanistan and Turkey.',method:'The original conference abstract and presentation details will be added once confirmed.',note:'Descriptive title; the exact paper title and original abstract are awaiting confirmation. Presented June 2020.',kind:'CreativeWork'},
];
export const cvSections = [
 {id:'education',title:'Education',entries:education.map(x=>({title:x.title,subtitle:x.institution,dates:x.dates,detail:`${x.result}. ${x.detail}`}))},
 {id:'research',title:'Research',entries:projects.filter(x=>x.kind==='Thesis').map(x=>({title:x.title,subtitle:x.institution,dates:String(x.year),detail:x.summary}))},
 {id:'conferences',title:'Conference presentations',entries:[{title:'Istanbul International Social Science Conference',subtitle:'Istanbul, Turkey',dates:'June 2020',detail:'Paper on the Global War on Terror and the roles of Afghanistan and Turkey in regional security. Exact paper title to be confirmed.'}]},
 {id:'teaching',title:'Teaching experience',entries:teaching.map(x=>({title:x.title,subtitle:x.institution,dates:x.dates,detail:x.detail}))},
 {id:'service',title:'Leadership & service',entries:[{title:'Student Affairs Sub-in-Charge',subtitle:'University of Gujrat, Mandi Bahauddin campus',dates:'During 2019–2022 appointment',detail:'Student affairs responsibilities and leadership of the Blood Donation Society.'}]},
 {id:'training',title:'Training',entries:[{title:'Protecting Human Research Participants',subtitle:'National Institutes of Health',dates:'',detail:'Research ethics training.'}]},
 {id:'skills',title:'Skills & languages',entries:[{title:'Research & teaching',subtitle:'',dates:'',detail:'Regional Security Complex Theory; SPSS; curriculum and resource design; inclusive teaching.'},{title:'Languages',subtitle:'',dates:'',detail:profile.languages.join(' · ')}]},
];
