'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
const ma='/research/afghanistan-regional-security';
const nodes=[
 {id:'russia',label:'RUSSIA',x:166,y:100,lx:166,ly:76,tip:'Russia: MPhil thesis, 2018',href:'/research/russia-afghanistan-relations'},
 {id:'central',label:'CENTRAL ASIA',x:395,y:168,lx:400,ly:142,tip:'Central Asia: a neighbouring region in my MA dissertation, 2024',href:ma},
 {id:'south',label:'SOUTH ASIA',x:382,y:378,lx:382,ly:412,tip:'South Asia: a neighbouring region in my MA dissertation, 2024',href:ma},
 {id:'gulf',label:'THE GULF',x:111,y:344,lx:111,ly:378,tip:'The Gulf: a neighbouring region in my MA dissertation, 2024',href:ma},
 {id:'turkey',label:'TURKEY',x:76,y:196,lx:80,ly:174,tip:'Turkey: Istanbul conference paper, 2020',href:'/research/istanbul-conference-2020'},
];
const centre={id:'afghanistan',x:260,y:260,tip:'Afghanistan: MA dissertation, 2024. From insulator to instigator',href:ma};
export function Constellation(){const router=useRouter();const [active,setActive]=useState<string|null>(null);const pointer=useRef({type:'mouse',wasOpen:false});
const current=[...nodes,centre].find(n=>n.id===active);
// The SVG scales with its box, so grow labels and tap areas as it shrinks: labels stay at least 12px and targets at least 44px on screen.
const svg=useRef<SVGSVGElement>(null);const [inv,setInv]=useState(1);
useEffect(()=>{const el=svg.current;if(!el)return;const ro=new ResizeObserver(([e])=>{const {width,height}=e.contentRect;const size=Math.min(width,height);if(size)setInv(520/size)});ro.observe(el);return ()=>ro.disconnect()},[]);
const label=Math.max(15,12.5*inv),centreLabel=Math.max(13,12.5*inv),ring=Math.max(58,centreLabel*3.6+8),hit=Math.max(26,23*inv);
// On touch, the first tap reveals the tooltip and the second opens the research.
function open(e:React.MouseEvent,n:{id:string;href:string}){e.preventDefault();if(pointer.current.type==='touch'&&!pointer.current.wasOpen){setActive(n.id);return}router.push(n.href)}
function handlers(n:{id:string;href:string;tip:string}){return {href:n.href,'aria-label':`${n.tip}. Read the research.`,onPointerDown:(e:React.PointerEvent)=>{pointer.current={type:e.pointerType,wasOpen:active===n.id}},onPointerEnter:(e:React.PointerEvent)=>{if(e.pointerType==='mouse')setActive(n.id)},onPointerLeave:(e:React.PointerEvent)=>{if(e.pointerType==='mouse')setActive(null)},onFocus:()=>setActive(n.id),onBlur:()=>setActive(null),onClick:(e:React.MouseEvent)=>open(e,n),className:active===n.id?'node active':'node'}}
return <div className="constellation"><div className="map"><svg ref={svg} viewBox="0 0 520 520" role="group" aria-labelledby="map-title map-desc"><title id="map-title">Afghanistan and its regional connections</title><desc id="map-desc">An abstract conceptual diagram connecting Afghanistan to Russia, Central Asia, South Asia, the Gulf and Turkey. Each region links to the related research. Positions are not geographic boundaries.</desc><defs><radialGradient id="halo"><stop stopColor="#b9a2ff" stopOpacity=".26"/><stop offset="1" stopColor="#b9a2ff" stopOpacity="0"/></radialGradient><linearGradient id="line"><stop stopColor="#b9a2ff"/><stop offset="1" stopColor="#7ee8df"/></linearGradient></defs><circle cx="260" cy="260" r="235" fill="url(#halo)"/><g fill="none" stroke="currentColor" opacity=".15"><circle cx="260" cy="260" r="105"/><circle cx="260" cy="260" r="175"/><circle cx="260" cy="260" r="228"/><path d="M32 260H488M260 32V488" strokeDasharray="2 8"/></g><g fill="none" stroke="url(#line)" strokeWidth="1.5" opacity=".65"><path d="M260 260Q175 170 166 100M260 260Q360 180 395 168M260 260Q370 310 382 378M260 260Q170 335 111 344"/><path d="M260 260Q150 215 76 196" strokeDasharray="4 6"/><path d="M166 100Q320 53 395 168M395 168Q485 270 382 378M382 378Q215 460 111 344" strokeDasharray="3 8" opacity=".35"/></g><g fill="var(--primary)" opacity=".6"><circle cx="340" cy="67" r="2"/><circle cx="224" cy="449" r="2"/><circle cx="451" cy="302" r="1.5"/></g>
<a {...handlers(centre)}><circle cx="260" cy="260" r={ring+8} className="hit"/><circle cx="260" cy="260" r={ring} fill="var(--surface)" stroke="var(--primary)" strokeOpacity=".6" className="ring"/><circle cx="260" cy="260" r={ring+8} fill="none" stroke="var(--primary)" strokeOpacity=".15"/><text x="260" textAnchor="middle" fontSize={centreLabel} letterSpacing={inv>1.1?0:.5} dominantBaseline="central" y="260">AFGHANISTAN</text></a>
{nodes.map(n=><a key={n.id} {...handlers(n)}><circle cx={n.x} cy={n.y} r={hit} className="hit"/><circle cx={n.x} cy={n.y} r="5" fill="var(--accent)" className="dot"/><text x={n.lx} y={n.ly} textAnchor="middle" fontSize={label} letterSpacing={inv>1.1?.5:1.5}>{n.label}</text></a>)}</svg>
{current&&<p className="map-tip" aria-hidden style={{left:`${current.x/5.2}%`,top:`${current.y/5.2}%`}}>{current.tip} <span aria-hidden>→</span></p>}</div><p className="mono">ONE COUNTRY. CONNECTED REGIONS.<span>Hover, tap or tab to a region to explore the research</span></p></div>}
